version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
    volumes:
      - .:/app  # Montar código para desarrollo
      - ./instance:/app/instance
    restart: unless-stopped
    command: python run.py  # Usar servidor de desarrollo de Flask