services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
    volumes:
      - db-data:/app/instance  # Usar volumen nombrado en lugar de bind mount
    restart: unless-stopped
    networks:
      - resort-network

networks:
  resort-network:
    driver: bridge

volumes:
  db-data: